import type { Metadata } from "next";
import "./globals.css";
import { connectToMongoDB } from "@/utils/db";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    connectToMongoDB();
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
